import './Content.css';
const Content=({post1Ref,post2Ref,post3Ref,post4Ref}) => {
  
return (
    <main className="content">
        <div className="section" id="post1" ref={post1Ref}>Anim dolore pariatur culpa dolor consequat ullamco labore officia ex pariatur nisi duis sed et voluptate cupidatat do ut labore culpa do mollit sint elit culpa dolore laboris voluptate anim sed ut aliquip enim labore ea dolore do do magna in nisi pariatur do aute quis sed in sunt et dolore do laboris veniam nisi irure sit ullamco sit do dolor fugiat do non pariatur eiusmod sint reprehenderit nisi velit velit deserunt elit sed occaecat cupidatat incididunt dolor qui ullamco commodo laboris ad consequat ut excepteur laboris nisi exercitation dolore incididunt in quis aliqua commodo veniam duis in veniam labore mollit reprehenderit non exercitation ullamco non aliqua cupidatat consectetur aute amet aute incididunt officia nostrud ut nulla nulla magna qui qui irure occaecat anim do amet enim in ut mollit exercitation id anim laboris sed eiusmod sit et aliqua veniam occaecat eu minim nostrud magna tempor ex nostrud consectetur culpa in non ea laboris sunt velit proident et est in ut ea nisi sed aliquip ullamco minim enim officia incididunt aliquip amet irure dolor eu veniam consectetur ut elit aliquip pariatur pariatur aliquip aliqua dolor consectetur esse ullamco ut laborum tempor id aliquip dolor in veniam sunt ex veniam laborum consequat ea dolore elit adipisicing laboris pariatur adipisicing nulla eu officia irure veniam ex eu elit aliqua nostrud tempor qui magna esse consectetur.Nulla amet laboris dolore commodo dolore consectetur ut veniam sed anim nostrud reprehenderit reprehenderit eiusmod fugiat tempor officia qui.</div>
        <div className="section" id="post2" ref={post2Ref}>In ut anim enim laborum eu laboris reprehenderit in laboris laborum ea eu amet velit ut pariatur non ut laborum ea dolore esse sed tempor velit deserunt quis aute excepteur tempor pariatur esse minim duis aliquip labore cupidatat in adipisicing laboris qui veniam voluptate officia minim enim sit officia minim elit aliquip enim proident et velit irure cupidatat culpa proident aliquip elit est ad fugiat non culpa et dolor dolore nostrud magna ex in duis ullamco et in nisi sunt laborum ut incididunt veniam amet enim cupidatat dolor esse minim culpa incididunt elit ut ex nisi occaecat minim fugiat do ut culpa nulla occaecat consectetur commodo ut consectetur proident aliqua commodo velit ut qui aliqua amet occaecat pariatur veniam aliqua consectetur in velit ut incididunt ut adipisicing duis occaecat duis id dolor nostrud ea culpa fugiat qui id ex minim do fugiat ut minim esse sunt culpa veniam eu sed mollit incididunt veniam ut quis in nostrud enim enim elit aliquip ut enim velit consequat irure laborum officia dolor ut magna ea ad laborum quis duis officia enim reprehenderit exercitation sed qui reprehenderit eu irure do mollit sit ex laborum exercitation elit irure dolor aute non id eu quis est.Minim exercitation eiusmod ullamco sed anim veniam culpa excepteur esse sint enim sint aliquip minim elit sit anim voluptate eu velit tempor quis fugiat dolore culpa reprehenderit irure consequat dolore ut voluptate velit.</div>
        <div className="section" id="post3" ref={post3Ref}>In in nulla qui esse cupidatat non ex duis aliqua amet sed quis irure incididunt ullamco nostrud occaecat sunt in sunt in in est quis mollit sint id ut cillum et velit adipisicing ad eiusmod in aliqua excepteur aliquip culpa ea quis dolore ad ea veniam sint excepteur ullamco ut adipisicing fugiat ut in commodo tempor officia duis pariatur dolor et eu id quis fugiat et fugiat dolore nulla do enim sint non fugiat sit incididunt in occaecat amet ut duis cillum occaecat dolore adipisicing dolor ut ut aliqua excepteur in veniam quis culpa ad anim incididunt proident sed aliquip sint voluptate nisi quis aliquip nisi ex quis qui irure nostrud elit aliqua sunt enim tempor anim ullamco fugiat quis cupidatat laborum id ut culpa id enim laboris fugiat dolor deserunt adipisicing fugiat duis consectetur aute consequat in irure reprehenderit sunt ut nulla id magna deserunt aliquip ullamco nisi excepteur excepteur eu sit nulla sunt.Do ex dolor proident labore consequat culpa dolor aliquip commodo dolor cupidatat culpa elit consectetur incididunt sed laboris cillum ex est eiusmod amet nulla anim do consequat.</div>
        <div className="section" id="post4" ref={post4Ref}>Minim irure tempor mollit cupidatat sunt veniam ut exercitation nostrud aliqua voluptate consectetur eu dolore est velit in occaecat aute aliqua eiusmod quis eiusmod in in aliquip dolore veniam esse incididunt proident nulla excepteur cillum eiusmod ut eu magna ea magna culpa esse excepteur ut esse anim et sint sed nisi eiusmod nulla magna commodo enim incididunt dolore eu est fugiat nostrud nulla fugiat officia ut nisi pariatur elit occaecat qui nisi aliquip aliqua cupidatat anim eiusmod mollit nisi velit anim voluptate proident est non duis labore ex non in ut labore deserunt occaecat amet ea ut labore enim aute elit incididunt in et eiusmod esse velit sint incididunt anim officia ea anim consequat enim dolore elit ex non anim occaecat exercitation do minim et qui irure incididunt pariatur officia dolor est qui irure do officia eu qui deserunt voluptate ex laborum commodo dolore amet cillum laborum adipisicing mollit labore excepteur occaecat est eu tempor voluptate dolor fugiat culpa mollit ex laboris sunt ullamco minim amet nostrud in aliquip.Lorem ipsum excepteur sit ea mollit esse qui in in pariatur deserunt reprehenderit ad minim commodo anim irure consequat dolore ea ex laboris do laborum. Lorem ipsum sit reprehenderit quis sint voluptate amet dolor nostrud fugiat velit eu cupidatat ad aliqua enim do elit pariatur exercitation incididunt aliqua incididunt nisi id cillum magna in consequat velit culpa reprehenderit in qui ex consequat est aliquip velit est nostrud duis ut nulla laboris velit dolore nisi ut in anim consequat do incididunt veniam magna nisi aute sunt qui irure cupidatat pariatur pariatur adipisicing eiusmod fugiat ut non anim elit aliqua minim exercitation ullamco sint pariatur pariatur magna dolor qui ea dolore eiusmod anim est consectetur in ut et duis mollit dolore elit qui exercitation qui eu do esse veniam qui amet aliqua laboris culpa ex magna elit dolor eu reprehenderit laboris ullamco minim magna anim dolore in ad pariatur adipisicing magna in dolore quis mollit ut anim pariatur mollit dolor ad ex esse occaecat ad in voluptate minim labore velit ad eiusmod dolore labore occaecat enim aliqua dolore veniam voluptate exercitation nostrud esse consequat magna eiusmod aliqua commodo veniam est ut non ullamco duis id eu nostrud anim.</div>

    </main>
  )
}
export default Content;

